### ISSUE TITLE
Remove dependency on KGuiAddons

### ISSUE THREAD

**Issue by paulolieuthier** [zjes/lxqt-kbdstate#1]
@zjes, now that it depends on xkbcommon for handling keymaps, it would be great to use that library for the special keys (Caps, Num, Scroll Locks) as well. Most of the code can be found in xkbcommon's test folder in the official repository:

https://github.com/xkbcommon/libxkbcommon/blob/master/test/interactive-x11.c
https://github.com/xkbcommon/libxkbcommon/blob/master/test/state.c

I've been experimenting with it, but couldn't get it to work so far (limited time).

Anyway, what's your opinion on that? Fewer dependencies means faster startup and more simplicity :smile:.

**Comment by zjes** [comment]
I'm agree, I've experimenting with it too and i will do it.

**Comment by zjes** [comment]
Done

**Comment by paulolieuthier** [comment]
You're fast. :+1:

**Comment by paulolieuthier** [comment]
It's actually faster now than before with KGuiAddons.

**Comment by zjes** [comment]
:D From now I will wait future of this project.
