### ISSUE TITLE
Problem with language variants

### ISSUE THREAD

**Issue by paulolieuthier** [zjes/lxqt-kbdstate#2]
This is the situation:

![screen](https://cloud.githubusercontent.com/assets/1238157/8333127/f934c8c8-1a67-11e5-9469-96b5e43e815e.png)

The first one, with no variant, is the one I use, and it correctly shows "BR" in the plugin:

![screen3](https://cloud.githubusercontent.com/assets/1238157/8333145/103a70cc-1a68-11e5-8463-6659008d9be9.png)

The other one, for some reason, doesn't show it:

![screen2](https://cloud.githubusercontent.com/assets/1238157/8333156/17f9b084-1a68-11e5-943a-fc6db383aab0.png)

**Comment by zjes** [comment]
Maybe here is problem, in systray shows synonym for language. But how to show lang+variant? 
In your case it will be BR,BR. It will be ok? Or you have some ideas how to show it?:)

**Comment by paulolieuthier** [comment]
How [qxkb](https://github.com/disels/qxkb) does it?

**Comment by paulolieuthier** [comment]
@agaida, give some help here, please.

**Comment by paulolieuthier** [comment]
Qxkb does not allow different variants for the same language. One has to choose one variant.

**Comment by zjes** [comment]
In xfce layout switcher shows synonyms, full name only in popup.
In your case it will be BR, BR... but i can show this variant like BR, BR(dvorak) (or show any sign), I don't like it, control in systray will be wider. Or, may be make configure of this label in configuration? Something like BR, BRD (user can change it)?
Last commit fix empty label, now it show lang without any variants (BR, BR)

**Comment by paulolieuthier** [comment]
I think only the language is enough for the label. The variant can go on a tooltip. In the tooltip, more information can be shown. Model, language and variant, one per line:
Model: Generic 104-key PC
Layout: Portuguese (Brazil)
Variant: None (or Nativo, Dvorak etc.)

Do you think that can be done?

**Comment by zjes** [comment]
In this case i only need show this wide tooltip. :)

**Comment by paulolieuthier** [comment]
And show show the language even in a different variant (to fix the issue).

**Comment by zjes** [comment]
it's already done.

**Comment by zjes** [comment]
Without keyboard model, i don't see any way how to grab it thru xkbcommon.
![tray](https://cloud.githubusercontent.com/assets/550431/8337990/71ccdd48-1aae-11e5-912c-1155e4f5d42e.png)

**Comment by paulolieuthier** [comment]
It's already enough.

**Comment by agaida** [comment]
cool
